[features]
seeds = false
skip-lint = false

[programs.localnet]
tienda_simple = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkgMQHgqE3s7P"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test"
